---
title: "Running ImageJ from make on multiple operating systems"
author: "J. R. Minter"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: united
    highlight: pygments
---

We want to use ``Gnu make`` to reproducibly process images with Fiji/ImageJ in the ``headless`` mode. Here we describe an approach that works on Windows, Linux, and MacOSX from a common code base. Getting this working on Windows was most difficult, so we present that as the base method.

## Install the Java Virtual Machines properly.

We will need to use environment variables and path names including spaces has caused errors. One needs to select a custom directory durning the installation process.  We also want multiple JVMs installed. Here are the paths I use in Windows 7 x64:

64 Bit JVMs:

```
C:\Apps\Java64\jdk1.6.0_45
C:\Apps\Java64\jdk1.7.0_75
C:\Apps\Java64\jdk1.8.0_31
```

and one 32 bit JVM (for the browser):

```
C:\Apps\Java32\jre1.8.0_31
```

Note that one can set up shortcuts to run the ImageJ/Fiji Gui from the Quick Launch bar that are stored here:

```
%appdata%\Microsoft\Internet Explorer\Quick Launch
```

I name the shortcuts `FijiJ6`, `FijiJ7`, and `FijiJ8`. Here are the entries for `FijiJ7`:

Target:

```
C:\Apps\Fiji.app.win64\ImageJ-win64.exe -Dpython.cachedir.skip=false --java-home "C:\Apps\Java64\jdk1.7.0_75" --
```

Run in:

```
C:\Apps\Fiji.app.win64
```

## Set up appropriate user environment variables.

Here are the User Environment variables I set from ``Computer > Properties > Advanced System Settings > Environment Variables``. Note: the first two need to be called by Git bash and need the `/C/` syntax...

```
BAD_DLL
/C/Users/{username}/AppData/Local/Temp/org.scijava.jython.shaded.jline_2_5_3.dll

BAD_TMP
/C/Users/{username}/AppData/Local/Temp


EDS_ROOT
C:/Data/eds

FIJI_APP
C:/Apps/Fiji.app.win64/ImageJ-win64.exe

FIJI_JAVA_HOME
C:/Apps/Java64/jdk1.7.0_75/jre

GIT_HOME
C:/Users/{username}/Documents/git

GITHOME
C:\Users\{username}\Documents\git
```

## Use a runFijiHeadless.sh shell script

This is the current version

```
#!/bin/bash
# use predefined variables to access passed arguments
#echo arguments to the shell
if [ -f $BAD_DLL ]
  then
    rm -rf $BAD_DLL
    rm -rf $BAD_TMP/j*.tmp
fi

if [ -f $1 ]
  then
    $FIJI_APP --java-home $FIJI_JAVA_HOME --mem=1000m --console --headless $1
  else
    echo $1 not found
fi


if [ -f $BAD_DLL ]
  then
    rm -rf $BAD_DLL
    rm -rf $BAD_TMP/j*.tmp
fi
```

### Generate a Makefile

Here is an example Makefile

```
# Example Makefile

dat/csv/latexPro.csv:
  cd sh; bash runFijiHeadless.sh "../py/makeLatexVertProf.py"

Sweave/inc/png/qm-nnnnn-sampleID-nnkV-map1.png:
	cd sh; bash runFijiHeadless.sh "../py/qm-nnnnn-sampleID-nnkV-map1/01-Prep-qm-nnnnn-sampleID-nnkV-map1.py"
	cd sh; bash runFijiHeadless.sh "../py/qm-nnnnn-sampleID-nnkV-map1/02-montage-qm-nnnnn-sampleID-nnkV-map1.py"
	
Sweave/inc/png/qm-nnnnn-sampleID-nnkV-map1-tol.png:
	cd sh; bash runFijiHeadless.sh "../py/qm-nnnnn-sampleID-nnkV-map1/01-Prep-qm-nnnnn-sampleID-nnkV-map1-tol.py"
	cd sh; bash runFijiHeadless.sh "../py/qm-nnnnn-sampleID-nnkV-map1/02-montage-qm-nnnnn-sampleID-nnkV-map1-tol.py"

all: Sweave/inc/png/qm-nnnnn-sampleID-nnkV-map1.png Sweave/inc/png/qm-nnnnn-sampleID-nnkV-map1-tol.png dat/csv/latexPro.csv

clean:
	rm -f Sweave/inc/png/qm-nnnnn-sampleID-nnkV-map1.png
	rm -f Sweave/inc/png/qm-nnnnn-sampleID-nnkV-map1-tol.png
	rm -f dat/csv/latexPro.csv

```

